[mgr]
ratio = [1, 3, 4]
sort_by       = "alphabetical"
sort_sensitive = false
sort_reverse  = false
sort_dir_first = false
show_hidden   = true
show_symlink = true
mouse_events = []

[preview]
wrap = "yes"

[opener]
open = [
    { run = '$OPENER "$@"', orphan = true, desc = "Open w/ default app", for = "linux" },
]

[open]
prepend_rules = [
    { mime = "application/zip", name = "*.lbx", use = "open" },
    { mime = "application/x-zip*", name = "*.lbx", use = "open" },
    { mime = "application/octet-stream", name = "*.lbx", use = "open" },
]
